- .github/workflows/pr_scan.yml
- Cartfile.resolved
Updates the embedded 3DS2 SDK to 2.1.0 RC5.
A test 3DS2 transaction.
> Update 3DS2 SDK to RC5

- .gitignore
1. Added the /Internal folder to .gitignore.
2. Added .gitmodules file to .gitignore.
> git ignored the Internal folder and .gitmodules file

- Adyen/Core/Payment Methods/AnyPaymentMethodDecoder.swift
- Adyen/Helpers/BundleHelpers.swift
- AdyenWeChatPay/WeChatPayActionComponent/WeChatPayActionComponent.swift
Renamed a few internal variables and methods to increase inclusivity.
> Rename internal variables for inclusivity

- Adyen/Components/Base/Component.swift
- AdyenDropIn/DropInComponent.swift
- fixed a small bug in Component.swift
> Small bug fix in Component.swift

- Adyen/Components/Redirect/WebRedirectComponent.swift
- Adyen/UI/UI Style/RedirectComponentStyle.swift
- AdyenTests/Adyen Tests/Components/Redirect/RedirectComponentTests.swift
Added modalPresentationStyle to RedirectComponentStyle.
Added a test case in RedirectComponentTests, to test ui configuration.
> Added modalPresentationStyle to RedirectComponentStyle.

- Adyen.podspec
- AdyenUIHost/Application/Configuration.swift
- Cartfile
Updated the 3DS SDK to 2.1.0-rc.6
> Updated the 3DS SDK to 2.1.0-rc.6

- Adyen.xcodeproj/project.pbxproj
- Adyen/Components/MB Way/MBWayComponent.swift
- Adyen/Components/MB Way/MBWayDetails.swift
- Adyen/Formatters/PhoneNumberFormatter.swift
- Adyen/UI/Form/FormViewController.swift
- Adyen/UI/Form/Items/FormItem.swift
- Adyen/UI/Form/Items/Phone Extension Picker/FormPhoneExtensionPickerItem.swift
- Adyen/UI/Form/Items/Text/FormTextItem.swift
- Adyen/Validators/EmailValidator.swift
- Adyen/Validators/NumericStringValidator.swift
- Adyen/Validators/PhoneNumberValidator.swift
- Adyen/Validators/RegularExpressionValidator.swift
- AdyenDropIn/Presentation/DropInNavigationController.swift
- AdyenTests/Adyen Tests/Components/Await Component/AwaitComponentTests.swift
- AdyenTests/Adyen Tests/Components/MB Way/MBWayComponentTests.swift
- AdyenTests/Adyen Tests/Components/Payment Method List/PaymentMethodListComponentTests.swift
- AdyenTests/Adyen Tests/Components/SEPA Tests/SEPADirectDebitComponentTests.swift
- AdyenTests/Adyen Tests/UI/PreselectedPaymentComponentTests.swift
- AdyenTests/Card Tests/BCMCComponentTests.swift
- AdyenTests/Card Tests/CardComponentTests.swift
- AdyenTests/Card Tests/Validators/PhoneNumberValidatorTests.swift
- AdyenUIHost/Application/Configuration.swift
1. Remove MBWay email field.
2. Fixe an issue with DropInNavigationController, where the preferred content size of content view controllers can be wrong.
3. Made the Phone number field in MBWayComponent accept any phone number from anywhere in the world.
4. Fixed Unit tests to reflect that any phone number is accepted.
5. Created a generic RegularExpressionValidator and made EmailValidator and PhoneNumberValidator inherit from it.
Covered the new logic with unit tests and modified the old unit tests.
> Fixed mb way component

- .github/workflows/pr_scan.yml
- Adyen.xcodeproj/project.pbxproj
- Adyen/Utilities/Throttler.swift
- AdyenCard/Components/Card/CardComponent.swift
- AdyenCard/Form/FormCardNumberItem.swift
- AdyenCard/Throttler.swift
- AdyenCard/Utilities/BinLookup/BinLookupRequest.swift
- AdyenCard/Utilities/BinLookup/BinLookupResponse.swift
- AdyenCard/Utilities/BinLookup/BinLookupService.swift
- AdyenCard/Utilities/CardType/CardTypeProvider.swift
- AdyenCard/Utilities/Encryption/CardEncryptor.swift
- AdyenCard/Utilities/Encryption/ObjC_CardEncryptor.h
- AdyenCard/Utilities/Encryption/ObjC_CardEncryptor.m
- AdyenTests/Card Tests/BCMCComponentTests.swift
- AdyenTests/Card Tests/CardComponentTests.swift
- AdyenTests/Card Tests/Form/FormCardNumberItemTests.swift
- AdyenTests/Card Tests/Mocks/CardTypeProviderMock.swift
- AdyenTests/Card Tests/Mocks/PublicKeyProviderMock.swift
- AdyenTests/Card Tests/Utilities/CardEncryptorCardTests.swift
- AdyenTests/Card Tests/Utilities/CardTypeProviderTests.swift
- AdyenTests/Card Tests/Utilities/ThrottlerTests.swift
- AdyenUIHost/Application/Configuration.swift
* fix payload encryption on BinLookup
* add throttling to BinLookup request
> Fix binlookup

- Adyen.podspec
updated 3ds 2 SDK to 2.1.0-rc.6
> updated 3ds2 SDK to 2.1.0-rc.6

- AdyenCard/Components/Card/CardComponent.swift
- AdyenCard/Form/FormCardNumberItem.swift
- AdyenTests/Adyen Tests/Components/Await Component/AwaitComponentTests.swift
- AdyenTests/Card Tests/BCMCComponentTests.swift
- AdyenTests/Card Tests/Form/FormCardNumberItemTests.swift
* Fix card number behaviour when no card is entered
* Code cleanup
* Fix tests
> Fix card detection UX

- .github/workflows/build.yml
- .github/workflows/pr_scan.yml
1. Ignore Sonar for forked PRs
2. Fix Dependency cache for master
3. Fix Xcode 12 build
> Update CI to ignore Sonar for forks and ignore Carthages

- .github/workflows/build.yml
- .github/workflows/pr_scan.yml
- Cartfile.resolved
* Fix Xcode 12 build and test
* Fix Carthage cache
> [WIP] Fix ci

- Adyen/Helpers/URLSessionHelpers.swift
- AdyenUIHost/Application/Configuration.swift
- Common Example code/Networking/DefaultAPIClient.swift
- Common Example code/Networking/Environment.swift
- Common Example code/PaymentsController.swift
chore: use direct checkout API during development, changed merchant account to TestMerchantCheckout, and added the client key query parameters to Environment.swift
> chore: Direct checkout api implementation

- .github/workflows/test-SPM-integration.yml
- .github/workflows/test-carthage-integration.yml
- Adyen.podspec
- Cartfile
- carthage.sh
- test-SPM-integration.sh
- test-carthage-integration.sh
chore: created a script to test SPM integration and added a CI work flow to run this script with PR's and merging with main branches
chore: created a script to test Carthage integration and added a CI work flow to run this script with PR's and merging with main branches
> Test SPM and Carthage integrations on CI

- README.md
Updated the README.md file to list Swift Package Manager as a way to integrate with iOS Components SDK.
> Updated the README.md file to list Swift Package Manager as a way to integrate with iOS Components SDK

- Adyen/Components/Base/PresentableComponent.swift
- AdyenCard/Components/Card/CardComponent.swift
- AdyenTests/Card Tests/CardComponentTests.swift
* pass payment from CardComponent to inner StoredCardComponent
> fix: passthrough payment to StoredCardComponent

- Adyen/Components/Base/ActionComponentData.swift
- Adyen/Components/Redirect/RedirectComponent.swift
- Adyen/Components/Redirect/WebRedirectComponent.swift
- Adyen/Core/Actions/RedirectAction.swift
- Common Example code/Networking/PaymentDetailsRequest.swift
chore: made paymentData in RedirectAction, RedirectComponent and ActionComponentData optional.
> chore: made paymentData in RedirectAction, RedirectComponent and ActionComponentData optional

- .github/workflows/build.yml
- .github/workflows/pr_scan.yml
- Adyen.xcodeproj/project.pbxproj
- Adyen.xcodeproj/xcshareddata/xcschemes/AdyenUIKitTests.xcscheme
- AdyenTests/Adyen Tests/Components/Apple Pay/ApplePayComponentTest.swift
* rename AdyenTests into AdyenUIKitTests and make it public scheme
* fix tests
* improve .yml files
> Fix legacy iOS 12 tests

- Adyen/Components/Redirect/WebRedirectComponent.swift
- AdyenTests/Adyen Tests/Components/Redirect/RedirectComponentTests.swift
* add callback on SFSafariViewController dismiss manually
> Callback on dismiss SFSafariViewController 

- Adyen/Components/MB Way/MBWayComponent.swift
- Adyen/Components/Qiwi Wallet/QiwiWalletComponent.swift
- Adyen/Components/SEPA Direct Debit/SEPADirectDebitComponent.swift
- Adyen/Utilities/LocalizationParameters.swift
- AdyenCard/Components/BCMC/BCMCComponent.swift
- AdyenCard/Components/Card/CardComponent.swift
- AdyenCard/Utilities/CardType/CardTypeDetector.swift
- AdyenCard/Utilities/Encryption/Cryptor/AES.swift
- AdyenDropIn/Utilities/ComponentManager.swift
- AdyenTests/Adyen Tests/Components/Apple Pay/ApplePayComponentTest.swift
- AdyenTests/Adyen Tests/Components/MB Way/MBWayComponentTests.swift
- AdyenTests/Adyen Tests/Components/Qiwi Wallet/QiwiWalletComponentTests.swift
- AdyenTests/Adyen Tests/Components/SEPA Tests/SEPADirectDebitComponentTests.swift
- AdyenTests/Adyen Tests/Utilities/ComponentManagerTests.swift
- AdyenTests/Card Tests/BCMCComponentTests.swift
- AdyenTests/Card Tests/CardComponentTests.swift
- AdyenTests/Card Tests/Utilities/CardTypeDetectorTests.swift
chore: Small fixes to unit tests and fixed many warnings
> chore: Small fixes to unit tests and fixed many warnings

- Adyen/UI/Form/Items/Basic Items/FormContainerItem.swift
- Adyen/UI/Form/Items/Basic Items/FormLabelItem.swift
> Fix SPM import UIKit

- Adyen/UI/Form/FormViewController.swift
* fix name conflict with Eureka
> Name conflict with Eureka

- .github/workflows/test_cocoapods_integration.yml
- test-CocoaPods-integration.sh
- test-SPM-integration.sh
chore: fix test-SPM-integration script and created test-CocoaPods-integration.sh script to test CocoaPods integrations properly.
> chore: fix test-SPM-integration script and created test-CocoaPods-integration.sh script to test CocoaPods integrations properly.

- Adyen.podspec
chore: suppress warnings  for cocoaPods integration.
> chore: suppress warnings  for cocoaPods integration

- Adyen.xcodeproj/xcshareddata/xcschemes/AdyenWeChatPay.xcscheme
chore: shared the AdyenWeChatPay.xcscheme for carthage to work.
> chore: shared the AdyenWeChatPay.xcscheme for carthage to work

- Adyen/UI/Form/Items/Basic Items/FormLabelItem.swift
* add private ADYLabel
* reuse it for AnyFormItemView instead of pure UILabel
> Fix: avoid hijacking `delegate` on UILabel

- README.md
chore: added some warnings to the README file about arm64 simulator builds.
> chore: added some warnings to the README file about arm64 simulator builds

- Adyen/Helpers/URLSessionHelpers.swift
chore: Modified URLSessionHelpers to send back an error in case of a non 200 status response with non-valid JSON response body.
> chore: Modified URLSessionHelpers to send back an error in case of a non 200 status response with non-valid JSON response body

- README.md
chore: Modified the README file warnings and added a link to the github issue where it addresses the warnings topic.
> chore: Modified the README file warnings and added a link to the github issue where it addresses the warnings topic

- AdyenCard/Components/BCMC/BCMCComponent.swift
- AdyenCard/Components/Card/CardComponent.swift
- AdyenDropIn/Models/PaymentMethodsConfiguration.swift
- AdyenDropIn/Utilities/ComponentManager.swift
- AdyenTests/Card Tests/BCMCComponentTests.swift
- AdyenTests/Card Tests/CardComponentTests.swift
feature: made a separate configuration for showing cvc field for normal card component and stored card component, to be configured separatly.
> feature: made a separate configuration for showing cvc field for normal card component and stored card component, to be configured separatly

- Adyen/Core/APIClient/APIClient.swift
- Adyen/Core/APIClient/APIError.swift
- Adyen/Helpers/URLSessionHelpers.swift
- Common Example code/PaymentsController.swift
chore: Modified URLSessionHelpers extension to avoid returning invalid JSON api response body when the response status code is not 200.
> chore: Modified URLSessionHelpers extension to avoid returning invalid JSON api response body when the response status code is not 200

- .github/workflows/publich_podspec.yml
chore: Added publich_podspec.yml work flow to manually publish the podspec file.
> chore: Added publich_podspec.yml work flow to manually publish the podspec file

- Adyen/Core/Payment Methods/AnyPaymentMethodDecoder.swift
- Adyen/Core/Payment Methods/IssuerListPaymentMethod.swift
- Adyen/Core/Payment Methods/PaymentMethods.swift
- AdyenTests/Adyen Tests/Core/BackoffSchedulerTests.swift
- AdyenTests/Adyen Tests/Core/PaymentMethodTests.swift
- AdyenTests/Adyen Tests/Core/TestPaymentMethodsJson.swift
- AdyenTests/Adyen Tests/Utilities/ComponentManagerTests.swift
- Common Example code/Networking/Environment.swift
chore: get rid of the dependency on the details object.
> chore: get rid of the dependency on the details object

- Adyen/Helpers/UIViewControllerHelpers.swift
chore: small fix in UIViewControllerHelpers.swift
> chore: small fix in UIViewControllerHelpers.swift

- Adyen.xcodeproj/project.pbxproj
- Adyen/Utilities/Analytics.swift
- AdyenCard/3DS2 Component/3DS2 Action handlers/AnyThreeDS2ActionHandler.swift
- AdyenCard/3DS2 Component/3DS2 Action handlers/ThreeDS2ClassicActionHandler.swift
- AdyenCard/3DS2 Component/3DS2 Action handlers/ThreeDS2CompactActionHandler.swift
- AdyenCard/3DS2 Component/3DS2 Action handlers/ThreeDS2CoreActionHandler.swift
- AdyenTests/Card Tests/3DS2 Component/ThreeDS2ClassicActionHandlerTests.swift
- AdyenTests/Card Tests/3DS2 Component/ThreeDS2CompactActionHandlerTests.swift
chore: refactored ThreeDS2CompactActionHandler and ThreeDS2ClassicActionHandler and put the common code in ThreeDS2CoreActionHandler
> chore: refactored ThreeDS2CompactActionHandler and ThreeDS2ClassicActionHandler and put the common code in ThreeDS2CoreActionHandler

- .github/workflows/build.yml
- .github/workflows/pr_scan.yml
*  Fix deprecated java version
*  Fix missing `refs/heads`
> Sonar warnings

- .github/workflows/build.yml
- .github/workflows/pr_scan.yml
> Fix CI Warnings 2: Sonar strikes back

- Adyen.xcodeproj/project.pbxproj
chore: added AdyenEncryption, AdyenActions targets to AdeynUIHost target as depedencies.
> chore: added AdyenEncryption, AdyenActions targets to AdeynUIHost target as depedencies

- Adyen.xcodeproj/project.pbxproj
- Adyen/Utilities/PhoneExtensionsRepository.swift
- AdyenComponents/MB Way/MBWayComponent.swift
- AdyenComponents/PhoneBasedPaymentComponent/PhoneBasedPaymentComponent.swift
- AdyenComponents/Qiwi Wallet/QiwiWalletComponent.swift
- AdyenDropIn/Presentation/DropInNavigationController.swift
- AdyenTests/Adyen Tests/Components/MB Way/MBWayComponentTests.swift
feature: Fixed MBWayComponent to show portugal and spain in the phone prefix drop down list of phone extensions.
chore: fixed the changing frame animation in DropInNavigationController when switching keyboards with different heights
> feature: Fixed MBWayComponent to show portugal and spain in the phone prefix drop down list of phone extensions.

- Adyen/Core/APIClient/Environment.swift
- Common Example code/Networking/Environment.swift
> Fix url for beta environment

- Adyen/Components/Await/AwaitComponent.swift
- AdyenDropIn/DropInActionComponent.swift
- AdyenDropIn/DropInComponent.swift
- AdyenTests/Adyen Tests/Components/Await Component/AwaitComponentTests.swift
- Common Example code/Assets/AdyenUIHost.strings
fix: custom localizationParameters wasn't being propagated to AwaitComponent.
> fix: custom localizationParameters wasn't being propagated to AwaitComponent

- .github/workflows/build.yml
- .github/workflows/pr_scan.yml
> Improve coverage

- .github/workflows/build.yml
- .github/workflows/pr_scan.yml
> Constrain Xcode version

- AdyenActions/Components/Redirect/RedirectDetails.swift
- Tests/AdyenTests/Adyen Tests/Components/Redirect Tests/RedirectDetailsTests.swift
* add support for return URL with`?pp=####` format
> Add 'returnUrlQueryString' option for RedirectDetails

- Adyen/UI/Form/Items/Phone Extension Picker/FormPhoneExtensionPickerItemView.swift
- Adyen/UI/Form/Items/Switch/FormSwitchItemView.swift
- Adyen/UI/Form/Items/Text/FormTextItemView.swift
- Adyen/UI/Form/Items/Value/FormValueItemView.swift
> Add tap recogniser to FormValueView

- AdyenCard/Components/Stored Card/StoredCardAlertManager.swift
- Tests/AdyenTests/Card Tests/StoredCardComponentTests.swift
> Limit CVC for stored card

- Adyen.xcodeproj/project.pbxproj
- Adyen/Core/Payment Methods/AnyPaymentMethodDecoder.swift
- Adyen/Core/Payment Methods/GiftCardPaymentMethod.swift
- Adyen/Core/Payment Methods/PaymentMethods.swift
- Adyen/Core/Payment Methods/RedirectPaymentMethod.swift
- AdyenDropIn/Components/PaymentMethodListComponent.swift
- Tests/AdyenTests/Adyen Tests/Core/PaymentMethodTests.swift
- Tests/AdyenTests/Adyen Tests/Core/TestPaymentMethodsJson.swift
- Tests/AdyenTests/Adyen Tests/Utilities/LogoGenerator.swift
* set `brand` as logo source for giftcard
> Fix giftcard logo

- AdyenComponents/Apple Pay/ApplePayComponent.swift
- Demo/Common/IntegrationExample.swift
- Demo/Common/IntegrationExampleComponents.swift
- Demo/Common/IntegrationExampleDropIn.swift
* remove cancelHandler from applePay
> Remove cancelHandler from applePay

- Adyen.xcodeproj/project.pbxproj
- Adyen/Core/Payment Methods/AnyPaymentMethodDecoder.swift
- Adyen/Core/Payment Methods/PaymentMethods.swift
- Adyen/Core/Payment Methods/StoredBLIKPaymentMethod.swift
- Adyen/Core/Payment Methods/StoredPayPalPaymentMethod.swift
- Tests/AdyenTests/Adyen Tests/Core/PaymentMethodTests.swift
- Tests/AdyenTests/Adyen Tests/Core/TestPaymentMethodsJson.swift
* add Stored BLIK Payment
* change display info for stored Paypal
> Stored Blik

- Adyen/Helpers/UIColorHelpers.swift
- Adyen/UI/UI Style/CoreColors.swift
- Adyen/UI/Views/CopyLabelView.swift
- AdyenActions/UI/View Controllers/Voucher/Doku Indomaret/DokuVoucherView.swift
- AdyenActions/UI/View Controllers/Voucher/VoucherCardView.swift
- AdyenActions/UI/View Controllers/Voucher/VoucherSeparatorView.swift
> UIColor namespace

- Adyen.xcodeproj/project.pbxproj
- Adyen/Helpers/UIViewControllerHelpers.swift
- AdyenActions/Components/Redirect/UniversalRedirectComponent.swift
- AdyenActions/UI/UI Style/RedirectComponentStyle.swift
- Demo/Common/IntegrationExample.swift
- Demo/UIKit/ComponentsViewController.swift
- Tests/AdyenTests/Adyen Tests/Components/Redirect/RedirectComponentTests.swift
* remove public helper for UIViewController
* make `preferredBarTintColor` optional and default value to **nil**
* add 1sec delay for UIKit Demo Alert presentation
> chore: minor cleanup

- .jazzy.yaml
- Adyen.podspec
- Adyen.xcodeproj/project.pbxproj
- AdyenComponents/Doku/DokuComponent.swift
- AdyenComponents/Doku/DokuDetails.swift
- README.md
- Tests/AdyenTests/Adyen Tests/Components/Doku/DokuComponentTests.swift
chore: renamed DokuWalletDetails to DokuDetails and added Doku Component and Voucher Component to jazzy.yaml file.
> chore: renamed DokuWalletDetails to DokuDetails and added Doku Component and Voucher Component to jazzy.yaml file

- Adyen.xcodeproj/project.pbxproj
- MIGRATION.md
- README.md
chore: added the MIGRATION.md file and made some changes to README.md with collaboration with Docs team.
> [WIP] chore: added the MIGRATION.md file and made some changes to README.md with collaboration with Docs team

- MIGRATION.md
> Update migration notes

- Adyen/Components/AbstractPersonalInformationComponent/AbstractPersonalInformationComponentExtensions.swift
- Adyen/Components/Base/PaymentComponent.swift
- Adyen/Components/Base/PresentableComponent.swift
- Adyen/UI/Form/FormViewController.swift
- Adyen/UI/List/ListViewController.swift
- AdyenCard/Components/Card/CardComponentExtensions.swift
- AdyenComponents/BLIK/BLIKComponent.swift
- AdyenComponents/Issuer List/IssuerListComponent.swift
- AdyenComponents/SEPA Direct Debit/SEPADirectDebitComponent.swift
- AdyenDropIn/Components/PreselectedPaymentMethodComponent.swift
- Tests/AdyenTests/Card Tests/CardComponentTests.swift
chore: make use of FormViewControllerDelegate in PreselectedPaymentMethodComponent, SEPADirectDebitComponent, and BLIKComponent.
> chore: make use of FormViewControllerDelegate in PreselectedPaymentMethodComponent, SEPADirectDebitComponent, and BLIKComponent

- AdyenDropIn/DropInComponent.swift
- AdyenDropIn/DropInComponentDelegate.swift
- Demo/Common/IntegrationExampleDropIn.swift
* `for paymentMethod: PaymentMethod` param in DropInDelegate.didSubmit
> [WIP] DropIn: selected payment method

- Adyen/Components/AbstractPersonalInformationComponent/AbstractPersonalInformationComponentExtensions.swift
- Adyen/Components/Base/Component.swift
- Adyen/Components/Base/LoadingComponent.swift
- Adyen/Core/Core Protocols/PresentableComponentWrapper.swift
- AdyenCard/Components/Card/CardComponent.swift
- AdyenComponents/BLIK/BLIKComponent.swift
- AdyenComponents/Issuer List/IssuerListComponent.swift
- AdyenComponents/SEPA Direct Debit/SEPADirectDebitComponent.swift
- AdyenDropIn/Components/PaymentMethodListComponent.swift
- AdyenDropIn/Components/PreselectedPaymentMethodComponent.swift
- AdyenDropIn/DropInComponent.swift
- Demo/Common/IntegrationExample.swift
- Demo/Common/IntegrationExampleComponents.swift
- MIGRATION.md
- Tests/AdyenTests/Adyen Tests/Components/Await Component/PollingAwaitComponentTests.swift
- Tests/AdyenTests/Adyen Tests/Components/BLIK Component/BLIKComponentTests.swift
- Tests/AdyenTests/Adyen Tests/Components/Base/IssuerListComponentTests.swift
- Tests/AdyenTests/Adyen Tests/Components/Doku/DokuComponentTests.swift
- Tests/AdyenTests/Adyen Tests/Components/MB Way/MBWayComponentTests.swift
- Tests/AdyenTests/Adyen Tests/Components/Payment Method List/PaymentMethodListComponentTests.swift
- Tests/AdyenTests/Adyen Tests/Components/Qiwi Wallet/QiwiWalletComponentTests.swift
- Tests/AdyenTests/Adyen Tests/Components/SEPA Tests/SEPADirectDebitComponentTests.swift
- Tests/AdyenTests/Adyen Tests/UI/PreselectedPaymentComponentTests.swift
- Tests/AdyenTests/Adyen Tests/UI/PresentableComponentMock.swift
- Tests/AdyenTests/Card Tests/BCMCComponentTests.swift
- Tests/AdyenTests/Card Tests/CardComponentTests.swift
feature: small refactoring to make it much easier to integrate for merchants with the different protocols Cancellable, Finalizable...etc.
> feature: small refactoring to make it much easier to integrate for merchants with the different protocols Cancellable, Finalizable...etc.

- Adyen.xcodeproj/project.pbxproj
- Demo/Common/Assets/AdyenUIHost.entitlements
> Xcodeproj refactor

- Adyen.xcodeproj/project.pbxproj
chore: make AdyenSwiftUI module support iOS 13.
> chore: make AdyenSwiftUI module support iOS 13

- .github/workflows/build.yml
- .github/workflows/format_project.yml
- .github/workflows/pr_scan.yml
- .github/workflows/regenerate-docs.yml
- .github/workflows/test-SPM-integration.yml
- .github/workflows/test-carthage-integration.yml
- .github/workflows/test_cocoapods_integration.yml
- .github/workflows/update-version.yml
- .swiftformat
chore: added a github manual workflow to format the whole project for release.
> chore: added a github manual workflow to format the whole project for release

- Adyen.xcodeproj/project.pbxproj
- AdyenCard/Components/Card/CardComponent.swift
- AdyenCard/Components/Card/CardComponentConfiguration.swift
- AdyenCard/Components/Card/CardComponentExtensions.swift
- AdyenCard/Components/Stored Card/StoredCardConfiguration.swift
- AdyenDropIn/Utilities/ComponentManager.swift
- Tests/AdyenTests/Card Tests/BCMCComponentTests.swift
* make standalone files for CardComponentConfiguration and StoredCardComponentConfiguration
* rename CardComponentConfiguration.supportedCards -> CardComponentConfiguration.allowedCards
* make CVC optional for encryption
* code cleanup
> Small fixes for CardComponent

- .jazzy.yaml
chore: updated the .jazzy.yml file to include the CardEncryptor, Card, and EncryptedCard in an Encryption category.
> chore: updated the .jazzy.yml file to include the CardEncryptor, Card, and EncryptedCard in an Encryption category

- AdyenDropIn/Models/PaymentMethodsConfiguration.swift
> Remove excludedCardNetworks

- MIGRATION.md
- README.md
chore: updated the readme file and migration md file
> chore: updated the readme file and migration md file

- Adyen/Utilities/LogoURLProvider.swift
- AdyenActions/Actions/AwaitAction.swift
- AdyenActions/Actions/ThreeDS2Action.swift
chore: fixed some public enums docs
> chore: fixed some public enums docs

- Adyen/Components/Base/PaymentComponent.swift
- Adyen/Components/Base/PresentableComponent.swift
- Adyen/Core/APIClient/Environment.swift
- Adyen/Core/Payment Methods/PaymentMethod.swift
- Adyen/Helpers/URLSessionHelpers.swift
- Adyen/UI/Form/Items/Basic Items/FormContainerItem.swift
- Adyen/UI/Form/Items/Text/FormTextItemView.swift
- Adyen/Utilities/Logger.swift
- AdyenActions/Actions/VoucherAction.swift
- AdyenCard/Utilities/BinLookup/BinLookupRequest.swift
- AdyenCard/Utilities/CardType/CardBrand.swift
- AdyenCard/Utilities/CardType/CardType.swift
- AdyenDropIn/Models/PaymentMethodsConfiguration.swift
- AdyenWeChatPay/WeChatPayActionComponent/WeChatPayActionComponent.swift
chore: fixed some missing docs
> chore: fixed some missing docs

- Adyen.xcodeproj/project.pbxproj
- Demo/Common/Helpers/APIClientHelper.swift
- Demo/Common/Utils/APIClientMock.swift
- Demo/Configuration.swift
* fix warnings about missing folder
* fix post-buld formatting and linting scripts
> chore: fix warnings

- Adyen.podspec
fix: fixed actions module resources access for cocoapods integration.
> fix: fixed actions module resources access for cocoapods integration

- Adyen.xcodeproj/project.pbxproj
- Adyen/UI/Form/FormViewController.swift
- AdyenCard/Components/Card/CardComponent.swift
- AdyenCard/Components/Card/CardComponentExtensions.swift
- AdyenCard/Components/Card/CardViewController.swift
- AdyenCard/Utilities/CardType/CardBrandProvider.swift
- AdyenCard/Utilities/CardType/FallbackCardBrandProvider.swift
- Tests/AdyenTests/Card Tests/BCMCComponentTests.swift
- Tests/AdyenTests/Card Tests/CardComponentTests.swift
- Tests/AdyenTests/Card Tests/Form/FormCardNumberItemTests.swift
- Tests/AdyenTests/Card Tests/Mocks/CardTypeProviderMock.swift
- Tests/AdyenTests/Card Tests/Utilities/CardBrandProviderTests.swift
* extract CardViewController from CardComponent
> Extract CardViewController form CardComponent

- Adyen.xcodeproj/project.pbxproj
- Adyen/UI/Form/FormViewController.swift
- AdyenDropIn/DropInComponent.swift
- AdyenDropIn/Models/PaymentMethodsConfiguration.swift
- AdyenDropIn/Utilities/ComponentManager.swift
- Demo/Common/IntegrationExampleDropIn.swift
- Tests/AdyenTests/Adyen Tests/UI/DropIn/DropInActionTests.swift
- Tests/AdyenTests/Adyen Tests/UI/DropIn/DropInTests.swift
- Tests/AdyenTests/Adyen Tests/Utilities/ComponentManagerTests.swift
* make `DropIn.PaymentMethodsConfiguration.applePay` optional property
* add init with required params to `DropIn.PaymentMethodsConfiguration. ApplePayConfiguration`
* DropIn and DropIn.ComponentManager refactoring
> Refactor drop in

- Adyen.xcodeproj/project.pbxproj
- Adyen/Components/AbstractPersonalInformationComponent/AbstractPersonalInformationComponentExtensions.swift
- Adyen/Helpers/UIViewConstraintsHelper.swift
- Adyen/Helpers/UIViewControllerHelpers.swift
- Adyen/UI/Form/FormItemViewBuilder.swift
- Adyen/UI/Form/FormViewController.swift
- Adyen/UI/Form/Items/Basic Items/FormLabelItem.swift
- Adyen/UI/Form/Items/Split/FormSplitItemView.swift
- Adyen/UI/List/ListViewController.swift
- Adyen/UI/UI Style/CoreColors.swift
- Adyen/UI/UI Style/CoreFonts.swift
- Adyen/UI/View Controllers/Secured View Controller/SecuredViewController.swift
- Adyen/UI/View Controllers/ViewControllerDelegate.swift
- Adyen/Utilities/LogoURLProvider.swift
- AdyenCard/Components/Card/CardComponent.swift
- AdyenCard/Components/Card/CardViewController.swift
- AdyenCard/Form/FormCardNumberItem.swift
- AdyenCard/Form/FormCardSecurityCodeItem.swift
- AdyenCard/Utilities/BinLookup/BinLookupResponse.swift
- AdyenCard/Utilities/CardType/CardBrandProvider.swift
- AdyenComponents/Apple Pay/ApplePayComponentExtensions.swift
- AdyenDropIn/Presentation/DropInNavigationController.swift
- AdyenDropIn/Presentation/ModalViewController.swift
- AdyenDropIn/Presentation/SlideInPresentationAnimator.swift
- AdyenDropIn/Presentation/WrapperViewController.swift
- AdyenDropIn/Views/ModalToolbar.swift
- Demo/UIKit/AppDelegate.swift
- Tests/AdyenTests/Adyen Tests/Components/Apple Pay/ApplePayComponentTest.swift
- Tests/AdyenTests/Card Tests/Form/FormCardNumberItemTests.swift
- Tests/AdyenTests/Card Tests/Form/FormCardNumberItemViewTests.swift
* make `minBinLength` 11
* move ViewControllerDelegate in standalone file
* improve UIView helpers
* move finalPresentationFrame to ModalViewController
* remove `#available(iOS 11.0, *)`
* remove environment from CardNumberItem. Use LogoProvider instead.
> Big refactoring

- Adyen.xcodeproj/project.pbxproj
- Adyen/Helpers/UIViewHelpers.swift
- Adyen/UI/Form/FormView.swift
- Adyen/UI/Form/FormViewController.swift
- Adyen/UI/Form/KeyboardAvoidingView.swift
- Adyen/Utilities/KeyboardObserver.swift
- AdyenActions/UI/View Controllers/Voucher/VoucherViewController.swift
- AdyenDropIn/Presentation/DropInNavigationController.swift
- AdyenDropIn/Presentation/WrapperViewController.swift
- Tests/AdyenTests/Adyen Tests/Helpers/UIViewHelpersTests.swift
chore: fixed a bug where formview's are not scrollable when the form is bigger than the screen height and the keyboard would cover most of the form.
> chore: fixed a bug where formview's are not scrollable when the form is bigger than the screen height and the keyboard would cover most of the form

- Adyen/Formatters/IBANFormatter.swift
- Adyen/Helpers/StringHelpers.swift
- Adyen/UI/Form/Items/Text/FormTextItemView.swift
- AdyenCard/Components/Card/CardViewController.swift
- AdyenCard/Formatters/CardExpiryDateFormatter.swift
- AdyenCard/Formatters/CardNumberFormatter.swift
- AdyenCard/Validators/CardExpiryDateValidator.swift
- Tests/AdyenTests/Adyen Tests/Extension Tests/StringExtensionsTests.swift
* move string helper under helper wrapper
> String helper

- Adyen/UI/Form/FormViewController.swift
- Adyen/UI/Form/FormViewItemManager.swift
- Adyen/UI/Form/Items/FormItem.swift
- Adyen/UI/Form/Items/FormItemView.swift
- Adyen/UI/Form/Items/Split/FormSplitItem.swift
chore: small refactoring in FormViewItemManager
> chore: small refactoring in FormViewItemManager

- Adyen.xcodeproj/project.pbxproj
- Adyen/Helpers/UIButtonHelpers.swift
- Adyen/Helpers/UILabelHelpers.swift
- Adyen/Helpers/UIProgressViewHelpers.swift
- Adyen/UI/Form/Items/Error/FormErrorItemView.swift
- Adyen/UI/Form/Items/Switch/FormSwitchItemView.swift
- Adyen/UI/Form/Items/Text/FormTextItemView.swift
- Adyen/UI/Form/Items/Value Pickers/Abstract/BasePickerInputControl.swift
- Adyen/UI/List/ListHeaderView.swift
- Adyen/UI/List/ListItemView.swift
- Adyen/UI/Views/CopyLabelView.swift
- Adyen/UI/Views/SubmitButton.swift
- AdyenActions/UI/View Controllers/Await View Controller/AwaitView.swift
- AdyenActions/UI/View Controllers/QR Code/QRCodeView.swift
- AdyenActions/UI/View Controllers/Voucher/AbstractVoucherView.swift
- AdyenActions/UI/View Controllers/Voucher/GenericVoucherView.swift
- Tests/AdyenTests/Adyen Tests/Extension Tests/UIButtonHelpersTests.swift
- Tests/AdyenTests/Adyen Tests/Extension Tests/UILabelHelpersTests.swift
This PR addes helper method and initializers to `UILabel` and `UIButton` that work with our defined `TextStyle` and `ButtonStyle`
> chore: Extract UIButton and UILabel style application

- AdyenComponents/Apple Pay/ApplePayComponentExtensions.swift
- MIGRATION.md
* send Apple Pay token as Base64
> Apple Pay token as base 64

- Adyen/Components/Base/AddressInfo.swift
- Adyen/Components/Base/PaymentComponentData.swift
- Adyen/Helpers/StringHelpers.swift
- AdyenCard/Components/Card/CardComponentConfiguration.swift
- AdyenCard/Components/Card/CardDetails.swift
- AdyenCard/Components/Card/CardViewController.swift
- Demo/Common/IntegrationExampleComponents.swift
- Demo/Common/IntegrationExampleDropIn.swift
- Tests/AdyenTests/Card Tests/CardComponentTests.swift
- Tests/AdyenTests/Card Tests/CardDetailsTests.swift
* add BillingAddressInformation
* unblock `zipCode` mode
* add single field for `zipCode` mode
> ZipCodeOonly billing address field

- AdyenActions/Actions/QRCodeAction.swift
- AdyenActions/AdyenActionComponent.swift
- AdyenActions/Components/3DS2/ThreeDS2Component.swift
- AdyenActions/Components/Await/AwaitComponent.swift
- AdyenActions/Components/QRCode/QRCodeComponent.swift
- AdyenActions/Components/Redirect/RedirectComponent.swift
- AdyenActions/Components/Voucher/VoucherComponent.swift
fix: ThreeDS2Component should take a presentation delegate and pass it on to the internal redirectComponent instance
> fix: ThreeDS2Component should take a presentation delegate and pass it on to the internal redirectComponent instance

- Adyen/Utilities/Localization.swift
This PR adds a fallback localization mechanism. In case current language does not have a translation for a specific key, an English translation will be used. We consider en-US `Localizable.strings` to be the most complete version.
> chore: Use en-US localization as a fallback if current language does not have a translation

- Adyen/Components/AbstractPersonalInformationComponent/AbstractPersonalInformationComponent.swift
- Adyen/Components/AbstractPersonalInformationComponent/EmailFormItemInjector.swift
- Adyen/Components/AbstractPersonalInformationComponent/NameFormItemInjector.swift
- Adyen/UI/Form/Items/Address/AddressViewModel.swift
- Adyen/UI/Form/Items/Address/FormFullAddressItem.swift
- Adyen/UI/Form/Items/Phone Number/FormPhoneNumberItemView.swift
- Adyen/UI/Form/Items/Text/FormTextItem.swift
- Adyen/UI/Form/Items/Text/FormTextItemView.swift
- AdyenCard/Components/Card/CardViewController.swift
- AdyenCard/Form/FormCardNumberItemView.swift
- Tests/AdyenTests/Card Tests/Form/FormItemViewBuilderTests.swift
* add contentType to TestFields on Address and PersonalInfoComponent
> Content type

- Adyen.xcodeproj/project.pbxproj
- Adyen/Helpers/UIViewConstraintsHelper.swift
- Adyen/UI/UI Style/NavigationStyle.swift
- AdyenDropIn/Presentation/WrapperViewController.swift
- AdyenDropIn/Views/ModalToolbar.swift
- Demo/SwiftUI/Info.plist
- Demo/UIKit/Info.plist
- Tests/AdyenTests/Adyen Tests/UI/ModalToolbarTests.swift
chore: Added arabic translations and used RTL language friendly autolayout constraints
> chore: Added arabic translations and used RTL language friendly autolayout constraints

- Adyen/UI/UI Style/NavigationStyle.swift
> chore: small docs fix

- Adyen/UI/UI Style/NavigationStyle.swift
- AdyenDropIn/Views/ModalToolbar.swift
- Demo/Configuration.swift
- Tests/AdyenTests/Adyen Tests/UI/ModalToolbarTests.swift
chore: fipped the ToolbarMode.natural convention so that the cancel button is on the left to RTL and on the right for LTR
> chore: fipped the ToolbarMode.natural convention so that the cancel button is on the left to RTL and on the right for LTR

- Adyen.xcodeproj/project.pbxproj
- Adyen/Components/Apple Pay/ApplePayComponent.swift
- Adyen/Helpers/UIViewControllerHelpers.swift
- Adyen/UI/ADYViewController.swift
- AdyenDropIn/Assets/DropInColors.swift
- AdyenDropIn/Components/PreApplePayComponent.swift
- AdyenDropIn/DropInComponent.swift
- AdyenDropIn/Utilities/ComponentManager.swift
- AdyenDropIn/Views/PreApplePayView.swift
- AdyenSwiftUI/ContentView.swift
- Common Example code/ComponentsItem.swift
- Common Example code/Domains/Components/ComponentsView.swift
- Common Example code/Domains/Components/ComponentsViewController.swift
* add PreApplePayViewComponent on DropIn
* add ApplePay button integration example
> V3 Apple pay button

- AdyenCard/Utilities/CardType/CardType.swift
- AdyenDropIn/Models/PaymentMethodsConfiguration.swift
- AdyenDropIn/Utilities/ComponentManager.swift
- AdyenTests/Card Tests/CardNumbers.swift
- Common Example code/PaymentsController.swift
* add 30xx cards to diners
* add showPostal to DropIn
* hide large title on BCMC DropIn
> V3 small fixes

- AdyenCard/Formatters/CardNumberFormatter.swift
* add grouping [4,6,4] for diners
> Fix grouping for diners

- Adyen/UI/Form/Items/Value Pickers/Phone Extension Picker/FormPhoneExtensionPickerItemView.swift
- AdyenActions/Components/Redirect/BrowserComponent.swift
- AdyenActions/Components/Redirect/RedirectComponent.swift
- AdyenDropIn/DropInComponent.swift
* fix SFSafariViewController false call of delegate.didCancel on app-to-app redirect
* fix UI for phone extension item
> Minor fixes

- AdyenActions/Components/Redirect/BrowserComponent.swift
- AdyenActions/Components/Redirect/RedirectComponent.swift
* call `didOpenExternalApplication` on redirecting app-to-app
> Add callback on app-to-app redirect

- AdyenDropIn/DropInComponent.swift
feature: expose CardComponentDelegate to dropin users
> feature: expose CardComponentDelegate to dropin users

- AdyenActions/Components/Await/AwaitComponent.swift
- AdyenActions/Components/Await/PollingHandlerProvider.swift
- AdyenActions/Components/QRCode/QRCodeComponent.swift
This PR refactors `AwaitComponent` , ﻿`PollingHandlerProvider` and `QRCodeComponent` to use less optional values.
> chore: Refactor AwaitComponent to use less optionals

- Adyen/Assets/Generated/LocalizationKey.swift
- Adyen/Assets/en-US.lproj/Localizable.strings
- AdyenDropIn/Utilities/ComponentManager.swift
chore: moved the hard coded string to the english strings file
> chore: moved the hard coded string to the english strings file

- AdyenCard/Components/Card/CardComponent.swift
- AdyenDropIn/Models/DropInConfiguration.swift
- AdyenDropIn/Utilities/ComponentManager.swift
- Demo/Common/IntegrationExampleComponents.swift
- Demo/Common/IntegrationExampleDropIn.swift
* provide default value for `configuration: Configuration` on `CardComponent.init`
> Add default value for Configuration on CardComponent.init

- AdyenComponents/Apple Pay/ApplePayComponent.swift
- AdyenComponents/Apple Pay/ApplePayComponentExtensions.swift
- AdyenDropIn/Components/PreApplePayComponent.swift
- AdyenDropIn/Models/DropInConfiguration.swift
- AdyenDropIn/Utilities/ComponentManager.swift
- Demo/Common/IntegrationExampleComponents.swift
- README.md
- Tests/AdyenTests/Adyen Tests/Components/Apple Pay/ApplePayComponentTests.swift
- Tests/AdyenTests/Adyen Tests/Components/Apple Pay/PreApplePayComponentTests.swift
* replace ApplePayConfiguration on DropIn with ApplePayComponent.Configuration
* refactor ApplePayComponent.Configuration
> DropIn.ApplePayConfiguration -> ApplePayComponent.Configuration

- .jazzy.yaml
- Adyen/Core/APIClient/Requests/ClientKeyRequest.swift
- Adyen/Core/APIClient/Requests/OrderStatusRequest.swift
- Adyen/Core/Core Protocols/ReadyToSubmitPaymentComponentDelegate.swift
- AdyenActions/AdyenActionComponent.swift
- AdyenActions/Components/3DS2/Action handlers/ThreeDS2CoreActionHandler.swift
- AdyenActions/Components/3DS2/ThreeDS2Component.swift
- AdyenComponents/Boleto/BoletoDetails.swift
- AdyenDropIn/DropInComponent.swift
- README.md
- Tests/AdyenTests/Card Tests/3DS2 Component/ThreeDS2ClassicActionHandlerTests.swift
- Tests/AdyenTests/Card Tests/3DS2 Component/ThreeDS2CompactActionHandlerTests.swift
- Tests/AdyenTests/Card Tests/3DS2 Component/ThreeDS2ComponentTests.swift
> Docs update proposal

- Adyen/Core/APIClient/APIContext.swift
- Adyen/Core/Components/Base/Component.swift
- Adyen/UI/Form/Items/Text/FormTextInputItem.swift
- AdyenActions/Actions/Action.swift
- AdyenActions/UI/View Controllers/Voucher/AbstractVoucherView.swift
- AdyenComponents/Boleto/BoletoComponentExtensions.swift
- Demo/Common/Configuration/ConfigurationView.swift
- Demo/Common/IntegrationExample.swift
- Demo/UIKit/ComponentsViewController.swift
- Tests/AdyenTests/Adyen Tests/Components/Await Component/AwaitComponentTests.swift
- Tests/AdyenTests/Adyen Tests/Components/Base/PartialPaymentDelegateMock.swift
- Tests/AdyenTests/Adyen Tests/Components/Base/ReadyToSubmitPaymentComponentDelegateMock.swift
- Tests/AdyenTests/Adyen Tests/Components/Boleto/BoletoComponentTests.swift
- Tests/AdyenTests/Adyen Tests/Components/Dummy.swift
- Tests/AdyenTests/Adyen Tests/Components/Gift Card/GiftCardComponentTests.swift
- Tests/AdyenTests/Adyen Tests/Components/Instant Payment Component Tests/InstantPaymentComponentTests.swift
- Tests/AdyenTests/Adyen Tests/Components/PaymentComponentMock.swift
- Tests/AdyenTests/Adyen Tests/Core/TestPaymentMethodsJson.swift
- Tests/AdyenTests/Adyen Tests/UI/DropIn/DropInTests.swift
- Tests/AdyenTests/Adyen Tests/Utilities/APIContextTests.swift
- Tests/AdyenTests/Adyen Tests/Utilities/BalanceCheckerTests.swift
- Tests/AdyenTests/Card Tests/3DS2 Component/AnyRedirectComponentMock.swift
- Tests/AdyenTests/Card Tests/CardDetailsTests.swift
> Format project

- AdyenActions/Components/Redirect/BrowserComponent.swift
- AdyenActions/UI/View Controllers/Await/AwaitView.swift
> chore: remove ios 11 checks

- Adyen/Helpers/UIViewHelpers.swift
- Adyen/UI/Form/FormViewController.swift
- Adyen/UI/Form/Items/Text/FormTextItemView.swift
- Adyen/UI/Form/Items/Value Pickers/Abstract/BaseFormPickerItemView.swift
- Adyen/UI/Form/Items/Value/FormValueItemView.swift
- Tests/AdyenTests/Adyen Tests/Components/Doku/DokuComponentTests.swift
- Tests/AdyenTests/Adyen Tests/Components/Seven Eleven Component/BasicPersonalInfoFormComponentTests.swift
chore: fixed the form text fields validation UI
> chore: fixed the form text fields validation UI

- Adyen.podspec
- Adyen.xcodeproj/project.pbxproj
- Adyen/Helpers/UIViewAnimation.swift
- Adyen/Helpers/UIViewHelpers.swift
- Adyen/UI/Form/FormViewController.swift
- Adyen/UI/Form/Items/Text/FormTextItemStyle.swift
- Adyen/UI/Form/Items/Text/FormTextItemView.swift
- Adyen/UI/Form/Items/Value/FormValueItemView.swift
- Cartfile
- Package.swift
- Tests/AdyenTests/Adyen Tests/UI/Form/Items/Text/FormTextItemViewTests.swift
- Tests/AdyenTests/Card Tests/Form/FormCardNumberItemViewTests.swift
chore: fixed the form validation status and highlighting and unhighlightinh of the separator and title, also fixed the overlapping animations.
> chore: fixed the form validation status and highlighting and unhighlightinh of the separator and title, also fixed the overlapping animations.

- .github/workflows/pr_scan.yml
- Adyen.xcodeproj/project.pbxproj
- AdyenCard/Components/Card/CardDetails.swift
- AdyenCard/Components/Card/ThreeDS2SdkVersion.swift
- Demo/Configuration.swift
- Scripts/validate-3ds2-SDK-version.sh
added validation to verify that the 3DS2 versions in podspec, cartfile, and SPM and ThreeDS2SdkVersion.swift all match
> added validation to verify that the 3DS2 versions in podspec, cartfile, and SPM and ThreeDS2SdkVersion.swift all match

- Adyen/UI/Form/Items/Text/FormTextItemView.swift
* show card brand logos after field is emptied
> Fix card logos

- AdyenCard/Components/Card/CardDetails.swift
> Fix 3DS parameter name

- Adyen.xcodeproj/project.pbxproj
- Adyen/Helpers/UIViewHelpers.swift
- Adyen/UI/Dimentions.swift
- Adyen/UI/Form/FormView.swift
- Adyen/UI/View Controllers/ADYViewController.swift
- AdyenActions/UI/View Controllers/Await/AwaitViewController.swift
- AdyenActions/UI/View Controllers/QR Code/QRCodeViewController.swift
- AdyenActions/UI/View Controllers/Voucher/VoucherViewController.swift
- AdyenDropIn/Presentation/ModalViewController.swift
- AdyenDropIn/Presentation/WrapperViewController.swift
* make max DropIn width for iPad 0.85% or 375px
* add `Dimentions` object
> Adjustable UI for iPad

- Adyen.xcodeproj/project.pbxproj
- Adyen/Formatters/BrazilSocialSecurityNumberFormatter.swift
- AdyenComponents/Boleto/BoletoComponent.swift
- Tests/AdyenTests/Adyen Tests/Components/Boleto/BoletoComponentTests.swift
Use formatting and validation of brazilian social security numbers in boleto component too.
> chore: add brazilian social security formatting to boleto component

- Adyen/UI/Form/Items/Address/AddressViewModel.swift
- Adyen/UI/Form/Items/Address/FormFullAddressItem.swift
- Tests/AdyenTests/Card Tests/CardComponentTests.swift
- Tests/AdyenTests/Card Tests/Form/FormItemViewBuilderTests.swift
* fix minimum length for house number on Address form
* support UK addresses
> Address fix

- AdyenCard/Form/FormCardSecurityCodeItem.swift
- Tests/AdyenTests/Card Tests/CardComponentTests.swift
Realized luhn check condition was wrong. Unit tests were missing too. Fixed and confirmed with unit tests
> fix: luhn check flag condition

- Adyen.xcodeproj/project.pbxproj
- Adyen/Validators/DateValidator.swift
- Adyen/Validators/LengthValidator.swift
- AdyenCard/Components/Card/CardViewController.swift
- AdyenComponents/BLIK/BLIKComponent.swift
- AdyenComponents/Boleto/BoletoComponent.swift
- Tests/AdyenTests/Adyen Tests/Utilities/DateValidationTests.swift
- Tests/AdyenTests/Adyen Tests/Utilities/LengthValidatorTests.swift
- Tests/AdyenTests/Card Tests/CardComponentTests.swift
* improve KCP validation
* add convenient init for LengthValidator
> Improve kcp validation

- AdyenCard/Components/Card/CardComponent.swift
- AdyenCard/Components/Card/CardComponentDelegate.swift
- AdyenCard/Components/Card/CardComponentExtensions.swift
- Demo/Common/IntegrationExampleComponents.swift
- Tests/AdyenTests/Adyen Tests/Components/Dummy.swift
- Tests/AdyenTests/Adyen Tests/Components/XCTestCaseExtension.swift
- Tests/AdyenTests/Card Tests/BCMCComponentTests.swift
- Tests/AdyenTests/Card Tests/CardComponentTests.swift
- Tests/AdyenTests/Card Tests/Mocks/CardComponentDelegateMock.swift
* add didSubmitLastFour to CardComponentDelegate
* add Dummy cards for testing
* add helper to populate card and submit button
> Add didSubmitLastFour to CardComponentDelegate

- Adyen/UI/Form/Items/Text/FormTextItemView.swift
- Adyen/UI/Form/Items/Text/TextField.swift
- Adyen/UI/Styles/TextStyle.swift
- AdyenCard/Form/FormCardSecurityCodeItemView.swift
- Tests/AdyenTests/Card Tests/CardComponentTests.swift
> CVC placeholder customisation

- AdyenCard/Components/BCMC/BCMCComponent.swift
- AdyenCard/Components/Card/CardComponent.swift
- AdyenCard/Components/Card/CardComponentExtensions.swift
- AdyenCard/Components/Card/CardViewController.swift
- AdyenCard/Utilities/CardType/BinInfoProvider.swift
- Tests/AdyenTests/Card Tests/Form/FormCardNumberItemTests.swift
- Tests/AdyenTests/Card Tests/Utilities/CardBrandProviderTests.swift
* move constants to standalone enum
> Move CardComponent constants to standalone enum

- .github/CODEOWNERS
- AdyenCard/Components/Card/CardComponentDelegate.swift
- AdyenCard/Components/Card/CardComponentExtensions.swift
- Demo/Common/IntegrationExampleComponents.swift
- Demo/Configuration.swift
- Tests/AdyenTests/Card Tests/Mocks/CardComponentDelegateMock.swift
chore: renamed didSubmitLastFour to didSubmit to make it more swifty
> chore: renamed didSubmitLastFour to didSubmit to make it more swifty

- Adyen/UI/Views/SubmitButton.swift
* apply "standard" corner rounding instead of mask for SubmitButton
> Fix border for submit button

- Adyen.xcodeproj/project.pbxproj
- Adyen.xcodeproj/xcshareddata/xcschemes/Localization.xcscheme
- Scripts/localization.sh
Added a localization target to make it easier for us to update content.
The script run by the target can be found in `Scripts`
> Create localization target

- Adyen.podspec
- Adyen.xcodeproj/project.pbxproj
- Cartfile
- Package.swift
Uses stable 1.0.0 networking SDK
> Uses stable 1.0.0 networking SDK

- Adyen/UI/Form/FormViewController.swift
- AdyenActions/Actions/VoucherAction.swift
> chore: fixed xcode warnings

- Adyen.podspec
- Adyen.xcodeproj/project.pbxproj
- AdyenCard/Components/Card/ThreeDS2SdkVersion.swift
- Cartfile
- Package.swift
feature: upgrade the 3ds2 SDK to 2.2.3.
> feature: upgrade the 3ds2 SDK to 2.2.3

- README.md
- Scripts/test-CocoaPods-integration.sh
chore: small fix to test-CocoaPods-integration.sh and README.md files
> chore: small fix to test-CocoaPods-integration.sh and README.md files

- Adyen/UI/Form/Items/Text/TextField.swift
> fix: naming conflict with Material lib

- Adyen.podspec
- Adyen.xcodeproj/project.pbxproj
> Release 4.2.0

- Adyen/Core/Components/AbstractPersonalInformationComponent/AbstractPersonalInformationComponent.swift
- Adyen/Formatters/Formatter.swift
- Adyen/UI/Form/FormViewController.swift
- Adyen/UI/Form/Items/Text/FormTextItem.swift
- Adyen/UI/Form/Items/Text/FormTextItemView.swift
- AdyenComponents/Boleto/BoletoComponent.swift
- AdyenDropIn/Utilities/ComponentManager.swift
- Tests/AdyenTests/Card Tests/CardComponentTests.swift
chore: fixed text items 2 way binding
- All unit tests are passing and the 2 way binding is working properly.
> chore: fixed text items 2 way binding

- Adyen/UI/Form/FormViewController.swift
* fix scrolling offset calculation
> v3: correct scrolling offset for reduced motion

- Adyen.xcodeproj/project.pbxproj
- Tests/AdyenTests/Adyen Tests/Components/Apple Pay/ApplePayComponentTests.swift
- Tests/AdyenTests/Adyen Tests/Utilities/AmountFormatterTests.swift
- Tests/AdyenTests/Adyen Tests/Utilities/Available.swift
chore: disables some unit tests on iOS 12 and below, since they are failing for weird reasons
> chore: disables some unit tests on iOS 12 and below

- Tests/AdyenTests/Card Tests/Utilities/ThrottlerTests.swift
chore: fixes ThrottlerTests falkiness
> chore: fixes ThrottlerTests falkiness

- Adyen.podspec
- AdyenCard/Components/Card/ThreeDS2SdkVersion.swift
- Cartfile
- Package.swift
Bumps 3DS2 SDK version to 2.2.4
> Bumps 3DS2 SDK version to 2.2.4

- AdyenDropIn/Presentation/DropInNavigationController.swift
- AdyenDropIn/Presentation/WrapperViewController.swift
chore: Fixes slide in animation
> chore: Fixes slide in animation

- AdyenActions/Components/Await/PollingComponent.swift
- Tests/AdyenTests/Adyen Tests/Components/Await Component/PollingComponentTests.swift
> fix: add error threshold to Polling Component

- .jazzy.yaml
- Adyen/UI/List/ListSection.swift
> chore: documentation fixes

- Adyen.podspec
- Adyen.xcodeproj/project.pbxproj
chore: Bumpes version to 4.4.0
> chore: Bumpes version to 4.4.0

- AdyenDropIn/Presentation/ModalViewController.swift
- AdyenDropIn/Presentation/WrapperViewController.swift
Fix bug on BLIK component where bottom offset is missing.
> Fix safeAreaInsets offset on BLIK component

- AdyenCard/Utilities/Encryption/CardEncryptor.swift
- AdyenCard/Utilities/Encryption/CardEncryptorExtensions.swift
fix: add generationDate to CardEncryptor.Card.encryptedToToken()
> fix: add generationDate to CardEncryptor.Card.encryptedToToken()

- .github/workflows/build.yml
- .github/workflows/format_project.yml
- .github/workflows/pr_scan.yml
- .github/workflows/publich_podspec.yml
- .github/workflows/regenerate-docs.yml
- .github/workflows/spell-check.yml
- .github/workflows/test-SPM-integration.yml
- .github/workflows/test-carthage-integration.yml
- .github/workflows/test_cocoapods_integration.yml
- .github/workflows/update-version.yml
- .gitignore
- Adyen.xcodeproj/project.pbxproj
- AdyenDropIn/Presentation/DropInNavigationController.swift
- Scripts/carthage.sh
- Scripts/test-carthage-integration.sh
- Tests/AdyenTests/Adyen Tests/Components/Apple Pay/ApplePayComponentTests.swift
- Tests/AdyenTests/Adyen Tests/Components/Await Component/AwaitComponentTests.swift
- Tests/AdyenTests/Adyen Tests/Components/Redirect/RedirectComponentTests.swift
- Tests/AdyenTests/Adyen Tests/Core/BackoffSchedulerTests.swift
- Tests/AdyenTests/Adyen Tests/DropIn/XCTestCaseExtensions.swift
- Tests/AdyenTests/Card Tests/CardComponentTests.swift
- Tests/AdyenTests/Card Tests/StoredCardComponentTests.swift
chore: update CI workflows into xcode 13
> chore: update CI workflows into xcode 13

- Adyen.xcodeproj/project.pbxproj
- Adyen/UI/Styles/ApplePayStyle.swift
- AdyenDropIn/Components/PreApplePayComponent.swift
- AdyenDropIn/Models/DropInComponentStyle.swift
- AdyenDropIn/Utilities/ComponentManager.swift
- AdyenDropIn/Views/PreApplePayView.swift
- Tests/AdyenTests/Adyen Tests/Components/Apple Pay/PreApplePayComponentTests.swift
UI configuration for Apple Pay component in the DropIn
> chore: add styling option for Apple Pay in dropin

- .typokana_ignore
- AdyenComponents/Apple Pay/ApplePayComponentExtensions.swift
- Tests/AdyenTests/Adyen Tests/Components/Apple Pay/ApplePayComponentTests.swift
* add Mada network to Apple Pay
* add CartesBancaires network to Apple Pay
> feature: add All available networks to apple pay

- Adyen.xcodeproj/project.pbxproj
> chore: Update version to 4.5.0

- Adyen.podspec
> Update podspec to 4.5.0

- Adyen.podspec
Release 4.5.0
**Fixed issue**:
> Release 4.5.0 (Update podspec)

- Adyen.xcodeproj/project.pbxproj
- Adyen/Helpers/NSConstraintHelper.swift
- Adyen/UI/Form/Items/Spacer/FormSpacerItemView.swift
- Adyen/UI/Form/Items/Text/TextField.swift
- Adyen/UI/List/ListCell.swift
- Adyen/UI/Views/SubmitButton.swift
* introduce new DSL for NSLayoutConstraint
* soften height constraints in FormSpacerItemView to fix NSLayoutConstraint error in logs
> fix: resolve NSLayoutConstraint errors in logs

- AdyenDropIn/DropInComponent.swift
- AdyenDropIn/Models/DropInConfiguration.swift
- Tests/AdyenTests/Adyen Tests/DropIn/DropInTests.swift
- allow skipping `PreselectedPaymentMethod` view
> feat: add `allowPreselectedPaymentView` to Drop-in

- .jazzy.yaml
> Update jazzy file with right references

- .github/workflows/test-carthage-integration.yml
* add `GITHUB_ACCESS_TOKEN` to Carthage script
> Fix Carthages

- AdyenCard/Components/Stored Card/StoredCardAlertManager.swift
> chore: fix retain cycle

- .github/workflows/publish-demo-app.yml
- .gitignore
- Scripts/publish-demo-app.sh
- exportOptions.plist
Implements the script that uploads the demo app to testflight and the github workflow
> Implements the script that uploads the demo app to testflight and the github workflow

- Adyen.xcodeproj/project.pbxproj
1. Remove duplicated dependencies due to `Adyen3DS2` and `AdyenActions` frameworks.
2. Discard dependency with `AdyenWeChatPay`.
3. Update Bundle IDs in order to submit build to App Store Connect.
> Remove duplicated dependencies

- .github/workflows/publish-demo-app.yml
- exportOptions.plist
Fixes the publish demo app GitHub action
> Fixes the publish demo app GitHub action

- .github/workflows/publish-demo-app.yml
- Adyen.xcodeproj/project.pbxproj
Publish demo app GitHub action fixes
> Publish demo app GitHub action

- Adyen.xcodeproj/project.pbxproj
> Bumps demo app build number

- Adyen.podspec
- Adyen.xcodeproj/project.pbxproj
chore: bumped version to 4.7.0
> chore: bumped version to 4.7.0

- AdyenComponents/Apple Pay/ApplePayComponent.swift
- AdyenComponents/Apple Pay/ApplePayComponentExtensions.swift
- AdyenWeChatPay/WeChatPayActionComponent/WeChatPayActionComponent.swift
- add message to Apple Pay when using simulator
-  un-document second WeChatPaySDKActionComponent
> Pre-release fixes

- .jazzy.yaml
- Adyen/Core/Payment Methods/WeChatPayPaymentMethod.swift
> Clean up .jazzy file

- Adyen/UI/Form/Items/Text/TextField.swift
* make `canPerformAction` fallback to default
> Correct input options
