Adyen/adyen-ios

- Adyen/Components/Apple Pay/ApplePayComponent.swift
"DropInComponent.stopLoading" was not called when canceling ApplePay
> Fix bug with applePay cencelation

- Adyen/Components/Await/AwaitComponent.swift
- AdyenCard/3DS2 Component/ThreeDS2Component.swift
- Cartfile
- Cartfile.resolved
1. Updated the 3DS2 SDK version to 2.2.0.
2. Fixed the messageVersion to 2.1.0 to avoid mass 3DS 2 errors because issuers might not be ready for 2.2.0.
3. A small fix in AwaitComponent to avoid crashes in production.
**Fixed issue**:  
1. fixed an issue where a fatal error is raised in `AwaitComponent` if `presentationDelegate` is nil.
2. Fixed the 3DS2 message version to be 2.1.0 in `ThreeDS2Component`.
> Updated the 3DS2 SDK version to 2.2.0.

- Adyen/UI/Checkout/CheckoutPresenter.swift
- Adyen/UI/Form/FormViewController.swift
- Podfile
- Podfile.lock
in cases:
1. Any payment method form that trigger a redirect (e.g Card form that trigger 3ds1 redirect).
2. Any redirect payment method like paypal for example.
and then the shopper cancel the safari screen.
Then:
dismiss the checkout all together.
> Dismiss the checkout all together when a web redirect is canceled

- Adyen/Core/Payment.swift
- Adyen/Utilities/AmountFormatter.swift
- AdyenTests/Adyen Tests/Utilities/AmountFormatterTests.swift
- Cartfile.resolved
My app stores prices in major units using `Decimal`, like so:
```swift
struct Price {
let amount: Decimal
let currencyCode: String
}
```
It's great for correctness, but not so great when trying to initialize a `Payment.Amount` because it only accepts minor units. The issue with minor units is that Adyen and iOS disagree on what a minor unit is for certain currencies, and I don't want to have to worry about that.
This change leverages the workarounds already implemented inside `AmountFormatter` to allow for the creation of a `Payment.Amount` using a `Decimal` value specified in major units. It applies proper rounding (towards zero).
All unit test scenarios for `AmountFormatter.minorUnitAmount(from: Double)`, but with `Decimal` values instead.
> Init Amount from a major unit Decimal

- AdyenCard/Components/Card/CardComponent.swift
- AdyenCard/Form/FormCardNumberItem.swift
- AdyenCard/Form/FormCardNumberItemView.swift
- AdyenCard/Utilities/CardType/CardTypeProvider.swift
- AdyenTests/Card Tests/BCMCComponentTests.swift
- AdyenTests/Card Tests/CardComponentTests.swift
- AdyenTests/Card Tests/Form/FormCardNumberItemTests.swift
- AdyenTests/Card Tests/Mocks/CardTypeProviderMock.swift
- AdyenTests/Card Tests/Utilities/CardTypeProviderTests.swift
- AdyenUIHost/Application/Configuration.swift
* CardNumberItem is no longer responsible for card type logo presentation logic - simply shows what is in there. All logic for limiting of max card type logos shown, invalid and empty states are moved to CardComponent. 
* rename some internal API
* refactor some internal logic
> Fix: improve card type detection visualisation

- Adyen/UI/SwiftUI/Present View Controller/ViewControllerPresenter.swift
Conditionally compile ViewControllerPresenter.swift file only in case the project is iOS 13+ and compiler can import SwiftUI and Combine
Tested archiving a release build of the SDK
**Fixed issue**: 
Fixed the issue where release builds are failing because we have minimum deployment target 10, but ViewControllerPresenter.swift requires iOS 13+, SwiftUI and Combine framework.
> Conditionally compile ViewControllerPresenter.swift file

- Adyen/Components/Apple Pay/ApplePayComponentExtensions.swift
While implementing Apple Pay in iOS using the Drop In SDK we noticed that when calling `stopLoading(withSuccess success: Bool, completion:)` method, that our completion block was never called. This meant that we were unable to finish our transaction when the Apple Pay sheet finishes dismissing.
This fix ensures that the `dismissCompletion` closure is captured in the dismiss closure and called. As far as I can tell, the closure was being deallocated before it could be called. Capturing it in the closure prevents this from happening and our closure is called successfuly and was also subject to a potential race condition where it could be set to nil before being called inside the closure.
We have tested this in our own application but this is a limited use case. I'd encourage testing in …
> Retains dismiss closure in Apple Pay

- .github/workflows/publich_podspec.yml
chore: added the COCOAPODS_TRUNK_TOKEN for publishing the Adyen.podspec.
> chore: added the COCOAPODS_TRUNK_TOKEN for publishing the Adyen.podspec

- Adyen/Components/Apple Pay/ApplePayComponent.swift
- Adyen/Components/Apple Pay/ApplePayComponentExtensions.swift
- AdyenTests/Adyen Tests/Components/Apple Pay/ApplePayComponentTest.swift
- Common Example code/Domains/Components/ComponentsViewController.swift
- Common Example code/PaymentsController.swift
* prevent ApplePay calling `delegate.didFail` on success
* add ApplePay component integration to ComponentsController
> ApplePay delegate.didFail fix

- Adyen/Helpers/UIViewHelpers.swift
- Adyen/UI/List/ListItem.swift
- Adyen/UI/List/ListItemView.swift
- AdyenDropIn/Components/PaymentMethodListComponent.swift
* add custom icon for ApplePay
* allow brand protected icons remain untampered on DropIn
> Brand-protected icons for payment methods

- Adyen/Core/Payment Methods/ApplePayPaymentMethod.swift
- AdyenComponents/Apple Pay/ApplePayComponent.swift
- AdyenComponents/Apple Pay/ApplePayComponentExtensions.swift
- AdyenDropIn/Utilities/ComponentManager.swift
- AdyenTests/Adyen Tests/Components/Apple Pay/ApplePayComponentTest.swift
- AdyenTests/Adyen Tests/Components/Apple Pay/ApplePayDetailsTest.swift
- Common Example code/Networking/Environment.swift
- Common Example code/PaymentsController.swift
* get list of supported networks for Applepay from paymentMethods
* ~~deprecate~~ remove excludedCardNetworks
> Supported networks Apple Pay from paymentMethods

- Adyen.xcodeproj/project.pbxproj
- Adyen.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
chore: use SPM instead of carthage for 3DS2SDK. Note: Carthage integration will still be broken, because Carthage still needs to implement XCFramework binary dependency [here](https://github.com/Carthage/Carthage/issues/3103)
> chore: use SPM instead of carthage for 3DS2SDK

- AdyenComponents/Apple Pay/ApplePayComponent.swift
- AdyenComponents/Apple Pay/ApplePayComponentExtensions.swift
- Tests/AdyenTests/Adyen Tests/Components/Apple Pay/ApplePayComponentTest.swift
* fix "sticky" paymentAuthorizationViewController proble
> Fix ApplePay test for iOS 11-12

- Package.swift
This PR tackles the issue described in #369 where compiling the Adyen SDK using Swift Package Manager results in a warning about a missing localization file.
At this time, I do believe this to be a bug with the way Apple has implemented the `defaultLocalization` parameter in Swift Package Manager. Apple's own documentation states that `defaultLocalization` should be a [LanguageTag](https://developer.apple.com/documentation/swift_packages/languagetag) which is an IETF language tag, in conformance with [RFC5654](https://tools.ietf.org/html/rfc5646).
The documentation of RFC5646 states that language tags should be case insensitive but does recommend capitalising the country code. Unfortunately it seems that Swift Package Manager does differentiate between upper and lower case characters and …
> Fixes localization warning when using SPM

- Adyen/Core/APIClient/APIClient.swift
Prevents caching of URLSession response by implementing a method from `URLSessionDataDelegate`.
**Note:** Implementing this requires `APIClient` to inherit from `NSObject`, which might impact performance. Another possible solution would be a separate delegate class, that only implements this method and is a property of `APIClient`
> fix: Prevent URLSession response from being cached

- Adyen/Core/APIClient/APIClient.swift
This sets a minimum TLS version to 1.2. Using `#available` here, can be dropped when support iOS 13+
> fix: set minimum required TLS version to 1.2

- AdyenActions/AdyenActionComponent.swift
- AdyenDropIn/DropInComponent.swift
- Demo/Common/IntegrationExampleComponents.swift
- Tests/AdyenTests/Adyen Tests/Components/AdyenActionComponentTests.swift
- Tests/AdyenTests/Adyen Tests/Utilities/AssertsTests.swift
This PR renames `perform(_ action: Action)` method in AdyenActionComponent to `handle(_ action: Action)` for consistency, since every other component has a `handle(_ action: Action)` method.
> chore: rename AdyenActionComponent method _handle_ to _perform_ for consistency

- Tests/AdyenTests/Card Tests/Utilities/CardEncryptorCardTests.swift
This PR fixes a warning caused by an `if #available(iOS 13.0, *)` check inside an `if #available(iOS 13.0, *)` check.
> chore: fix warning caused by a redundant iOS version check

- Adyen/Helpers/UIViewRoundingHelpers.swift
This PR ensures we use `.continuous` rounded corner style by default as per Apple's design guidelines.
> chore: Use continuous curve by default when rounding corners

- AdyenActions/UI/View Controllers/Voucher/GenericVoucherView.swift
- AdyenActions/UI/View Controllers/Voucher/GenericVoucherViewModel.swift
- AdyenActions/UI/View Controllers/Voucher/VoucherSeparatorView.swift
- Demo/Configuration.swift
This PR will use `TextStyle` fonts instead of hardcoded sizes in `GenericVoucherView` for better accessibility when using larger font sizes.
> Use TextStyle fonts on GenericVoucherView 

- AdyenActions/Components/QRCode/QRCodeComponent.swift
- AdyenActions/UI/UI Style/QRCodeComponentStyle.swift
- AdyenActions/UI/View Controllers/QR Code/QRCodeView.swift
- AdyenActions/UI/View Controllers/QR Code/QRCodeViewModel.swift
- Tests/AdyenTests/Adyen Tests/Components/PIX/QRCodeComponentTests.swift
This PR adds rounded corners to PIX logo so it looks better in dark mode
> chore: Set rounded corners for PIX logo

- AdyenActions/Actions/Action.swift
- AdyenActions/Actions/QRCodeAction.swift
- Tests/AdyenTests/Adyen Tests/Core/ActionTests.swift
This PR will fix the issue when BCMC_Mobile was treated as a `QRCodeAction`. Instead it will be parsed into a `RedirectAction` and handled appropriately.
> fix: Treat BCMC_Mobile as RedirectAction instead of QRCodeAction

- AdyenCard/Components/Card/CardDetails.swift
- AdyenCard/Components/Card/CardViewController.swift
- AdyenComponents/BasicPersonalInfoFormComponent/BasicPersonalInfoFormDetails.swift
- Tests/AdyenTests/Card Tests/CardDetailsTests.swift
* move "Remember for next time" below PostCode field
* remove `billing address` from CardDetails decoder
> Fix payment details

- Adyen/Helpers/UIViewConstraintsHelper.swift
- AdyenActions/UI/View Controllers/QR Code/QRCodeView.swift
- AdyenDropIn/Views/PreApplePayView.swift
This PR will fix issue when QRCodeView and PreApplePayView subviews were not using `safeAreaLayoutGuide.leadingAnchor` and `safeAreaLayoutGuide.trailingAnchor`, causing them to look wrong in landscape orientation.
> fix: Fix constraints on QRCodeView and PreApplePay view not using safeAreaLayoutGuide

- AdyenActions/Components/Redirect/RedirectDetails.swift
- Tests/AdyenTests/Adyen Tests/Components/Redirect Tests/RedirectDetailsTests.swift
This submits `returnUrlQueryString` if no known values are found in the redirect parameters. This adds support for direct issuer links.
> fix: Use returnUrlQueryString for entire URL query

- Adyen.xcodeproj/project.pbxproj
This PR improves the trigger for `LocalizationKey.swift` generated. Now a new version will be created when any changes in `Adyen/Assets/en-US.lproj/Localizable.strings` are detected, does not matter if the file is staged or not.
> chore: Generate new localization keys independent of whether Localizable.strings were staged or not

- AdyenActions/Actions/Action.swift
Added backticks to the `await` case of the `Action` enum to prevent issues with iOS 15s new async/await keywords
> chore: add backticks to await case in advance of ios15 async/await

- AdyenCard/Components/Card/CardViewController.swift
- AdyenCard/Form/FormCardNumberItem.swift
- AdyenCard/Form/FormCardSecurityCodeItem.swift
- AdyenCard/Utilities/CardType/CardBrand.swift
- AdyenCard/Validators/CardNumberValidator.swift
- Tests/AdyenTests/Card Tests/Validators/CardNumberValidatorTests.swift
Check for enableLuhnCheck flag in BinLookupResponse brands to allow for luhn check validation.
**Fixed issue**:  [COIOS-472](https://youtrack.is.adyen.com/issue/COIOS-472)
> feature: disable luhn check if flag is false in binlookup

- Adyen/Helpers/StringHelpers.swift
- Tests/AdyenTests/Adyen Tests/Extension Tests/StringExtensionsTests.swift
- Tests/AdyenTests/Card Tests/CardComponentTests.swift
Prevent out of bonds access on string subscript via ranges
Safety checks of ranges on the public subscript string extensions for open/closed ranges to prevent out of bonds crashes.
Tested with all possible ranges with non-empty & empty strings.
> chore: safe range access on string extension

- AdyenCard/Form/FormCardNumberItemView.swift
fix: changed credit card textfield returnKeyType to default
We noticed that keyboard type of credit card textfield in drop in component was changed after migratiion from Adyen iOS 3.8.4 to 4.0.0 .
Previously .numberPad keyboard type was displayed. Now the keyboard with .numbersAndPunctuation appears instead of it.
The root issue is the iOS bug which happens if textContentType is set to .creditCardNumber and and returnKeyType is not default.
ReturnKeyType was changed long ago and textContentType was added in 4.0.0 update, that's why it breaks.
My suggestion is to override the returnKeyType for CardNumberItemView with default value. 
Return button is not displayed for .numberPad keyboard so this fix wont affect the UI.
> fix: changed credit card textfield returnKeyType to default

- Adyen/UI/Form/FormViewController.swift
- AdyenDropIn/Presentation/DropInNavigationController.swift
Keyboard observers were not being removed on deinit since they are re-assigned as `void`s in the calling classes instead of NSObverservers as the initial assignment.
**Fixed issue**:
> fix: removing keyboard observers

- AdyenCard/Components/Card/CardViewController.swift
- Tests/AdyenTests/Card Tests/CardComponentTests.swift
Now checks bin lookup response based on config (.auto), instead of always checking binlookup.
> chore: fix displaying social security field based on config

- Adyen/UI/SwiftUI/Present View Controller/ViewControllerPresenter.swift
* ignore non-armv7 archt for SwiftUI helpers
> v3: fix armv7 for SwiftUI

- AdyenCard/3DS2 Component/ThreeDS2Component.swift
- AdyenCard/3DS2 Component/ThreeDS2ComponentFingerprintToken.swift
fix: use the dynamic messageVersion passed with the three DS 2 fingerprint token message version and not hardcoding the message version to 2.1.0
> fix: use the dynamic messageVersion passed with the three DS 2 fingerprint token

- AdyenCard/Components/Card/CardViewController.swift
- AdyenCard/Form/FormCardLogosItemView.swift
- AdyenCard/Form/FormCardNumberContainerItem.swift
- AdyenCard/Form/FormCardNumberItemView.swift
- Tests/AdyenTests/Card Tests/CardComponentTests.swift
Add an alpha for the card logos based on brand is detected or not.
> chore: change alpha of supported card logos if brand is detected

- Adyen/UI/Form/Items/Toggle/FormToggleItemView.swift
Fixed layout bug on the switch view within the `FormToggleItem` when used with long texts.
> fix: Fix layout issue on switch view when used with large text

- AdyenDropIn/DropInComponent.swift
- AdyenDropIn/DropInComponentExtensions.swift
- AdyenDropIn/Models/DropInConfiguration.swift
- AdyenDropIn/Utilities/ComponentManager.swift
- Tests/AdyenTests/Adyen Tests/DropIn/DropInTests.swift
Added a configuration flag to allow skipping payment list on drop in when there is only one non-instant payment method.
> Option to skip payment list on dropin when single regular method

- AdyenCard/Components/Card/CardComponent.swift
- AdyenComponents/Apple Pay/ApplePayComponent.swift
- AdyenComponents/Apple Pay/ApplePayComponentExtensions.swift
- Demo/Common/IntegrationExample.swift
- Demo/Common/IntegrationExampleComponents.swift
- Demo/Common/IntegrationExampleDropIn.swift
- safeguard apple-pay calling `didFail` on successful payment
- disable UI for presented payment component while `/payment/details` call
> Prevents apple pay call didFail on success

- AdyenActions/Components/Redirect/BrowserComponent.swift
increase the time delay in BrowserComponent before calling didCancel() or didOpenExternalApplication() to 1 second instead of 25 milliseconds.
> fix a bug with `BrowserComponent`
